# Basic provisioning example
- name: Create an EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
   - name: webservers security group
     ec2_group:
      name: ec2-security-group
      description: "A Security group"
      region: "{{aws_region}}"
      rules:
       - proto: tcp
         from_port: 22
         to_port: 22    
         cidr_ip: 0.0.0.0/0
  
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
      
      rules_egress:
       - proto: all
         cidr_ip: 0.0.0.0/0
   
   - name: webserver_01
     ec2:
       key_name: "{{key_name}}"
       region: "{{aws_region}}"
       group: ec2-security-group
       instance_type: "{{instance_type}}"
       count: 1
       image: "{{ami_id}}"
       wait: yes
     register: ec2
   - name: Waiting for instance to boot
     wait_for:
       host: "{{ item.public_dns_name }}"
       port: 22
       delay: 90
       timeout: 300
       state: started
     with_items: ec2.instances
